Update contributing.md for Windows contributors
Went through the steps on my Windows development machine and ran into errors (below). Discovered that this was likely Windows specific and wanted to simply update this so others can avoid similar issues.

Also updated some of the bash commands so that they highlighted having an activated virtual environment for consistency.

Complete output (1 lines):
    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.