build+docs: use Python 3.8 - 3.11 and pin pytest 8.1.1
-   `conda create -n plotly-dev python` currently gives Python 3.12.3.
-   `pytest -v packages/python/plotly/plotly/tests/` then fails with `ModuleNotFoundError: No module named 'imp'`.
    -   `pip install imp` fails: the `imp` module was deprecated in Python 3.11 and has been removed in Python 3.12.
-   So update `contributing.md` to specify `conda create -n plotly-dev python=3.11`
-   But now `pytest` fails
    -   `File "<frozen importlib._bootstrap>", line 1072, in _find_spec`
    -   `AttributeError: 'AssertionRewritingHook' object has no attribute 'find_spec'`
-   Problem was `pytest==3.5.1` in `packages/python/plotly/optional-requirements.txt`
-   Update to `pytest==8.1.1` and `pytest` runs
    -   Some tests are failing (orca problems, `statsmodels` not installed, etc.)
    -   Will fix these in separate PRs
-   Update `contributing.md` to state that we've tested changes against Python 3.8-3.11
    -   Specifically 3.8.19, 3.9.19, 3.10.14, and 3.11.9 on MacOS Sonoma 14.4.1
-   Update `CHANGELOG.md`