Improved error message when subscripting types that don't support it
For example, `fig.update_layout(width_x=1)` gives the following error
message:

TypeError: 'NoneType' object is not subscriptable

Invalid value received for the 'width' property of layout

    The 'width' property is a number and may be specified as:
      - An int or float in the interval [10, inf]

Property does not support subscripting:
width_x
~~~~~

because `fig.layout['width']` can't be subscripted (you can't do
`fig.layout['width']['x'] = 1`)