Import problem does not work in Jupyter lab
Should this be 'uninstall' instead of 'remove'?

`$ pip remove plotly` gives:
```
ERROR: unknown command "remove"
```
in JupyterLab -> Terminal v2.2.8 on Windows 10.