Fix improper JSON encoding exception when pillow module not installed (#1993)
4.4.0 regression. When the pillow module is not installed, and an attempt is made to JSON serialize a figure that includes unsupported object types, an "AttributeError: 'NoneType' object has no attribute 'Image'" exception was raised.

With this fix, the proper TypeError exception is raised once more.