Update _facet_grid.py
I was getting error that kwargs is undefined:

```NameError                                 Traceback (most recent call last)
<ipython-input-173-30fb7f3aeb2e> in <module>()
      9     facet_row='cut',
     10     color_name='depth',
---> 11     facet_col='z'
     12 
     13 )

/home/alishobeiri/anaconda2/lib/python2.7/site-packages/plotly/figure_factory/_facet_grid.pyc in create_facet_grid(df, x, y, facet_row, facet_col, color_name, colormap, color_is_cat, facet_row_labels, facet_col_labels, height, width, trace_type, scales, dtick_x, dtick_y, show_boxes, ggplot2, binsize, **kwargs)
    867                     facet_row_labels, facet_col_labels, trace_type,
    868                     flipped_rows, flipped_cols, show_boxes, marker_color,
--> 869                     kwargs_trace, kwargs_marker
    870                 )
    871 

/home/alishobeiri/anaconda2/lib/python2.7/site-packages/plotly/figure_factory/_facet_grid.pyc in _facet_grid_color_numerical(df, x, y, facet_row, facet_col, color_name, colormap, num_of_rows, num_of_cols, facet_row_labels, facet_col_labels, trace_type, flipped_rows, flipped_cols, show_boxes, marker_color, kwargs_trace, kwargs_marker)
    414                         type=trace_type,
    415                         showlegend=False,
--> 416                         **kwargs
    417                     )
    418                 fig.append_trace(trace, row_count + 1, col_count + 1)

NameError: global name 'kwargs' is not defined ```

Thought it might be because kwargs should actually be kwards_trace - not sure tho